#!/bin/bash

# Exit if sub command returns non zero
set -e

# Run rubocop
if [ -f bin/rubocop ]; then
  echo "Running Rubocop"
  bin/rubocop
fi

# Run reek
if [ -f bin/reek ]; then
  echo "Running Reek"
  bin/reek
fi
